[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "i686-radiumos.json"

[target.i686-radiumos]
rustflags = [
    "-C", "relocation-model=static",
    "-C", "code-model=kernel",
]
